In [9]:
import numpy as np

In [3]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [4]:
#concatenating arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1, 1])

concat = np.concatenate([x, y])
print("\n", concat)


 [1 2 3 3 2 1 1]


In [5]:
array_one = np.full((5,4), 3.14)
print("\n", array_one)

print(array_one.shape)
print(array_one.size)
print(array_one.dtype)



 [[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]
(5, 4)
20
float64


In [7]:
print(np.array([1, 2, 3, 4], dtype = 'int'))

print(np.zeros(3))
print(np.ones(5))

[1 2 3 4]
[0. 0. 0.]
[1. 1. 1. 1. 1.]


In [ ]:
#formatting arrays with vertical stacking
vertical_stack = np.array([1, 2, 3, 4])
vertical_stack_two = np.array([9,8,7,6], [6,5,4,3,2])

In [1]:
import seaborn as sns